version: '3.8'

services:

  postgres_payment: # This is correctly nested
    image: postgres:15-alpine
    container_name: postgres_payment
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpassword
      POSTGRES_DB: paymentdb
    volumes:
      - ./postgres-data/payment:/var/lib/postgresql/datastgres-data/payment:/var/lib/postgresql/data